export const BLANKAVG = [
  { name: 'ast' },
  { name: 'blk' },
  { name: 'dreb' },
  { name: 'fg_pct' },
  { name: 'fg3_pct' },
  { name: 'fg3a' },
  { name: 'fg3m' },
  { name: 'fga' },
  { name: 'fgm' },
  { name: 'ft_pct' },
  { name: 'fta' },
  { name: 'ftm' },
  { name: 'games_played' },
  { name: 'min' },
  { name: 'oreb' },
  { name: 'pf' },
  { name: 'player_id' },
  { name: 'pts' },
  { name: 'reb' },
  { name: 'season' },
  { name: 'stl' },
  { name: 'turnover' },
]

export const BLANKAVGOBJ = {
  "games_played": null,
  "Player_id": null,
  "season": null,
  "min": null,
  "fgm": null,
  "fga": null,
  "fg3m": null,
  "fg3a": null,
  "fga": null,
  "ftm": null,
  "oreb": null,
  "dreb": null,
  "reb": null,
  "ast": null,
  "stl": null,
  "blk": null,
  "turnover": null,
  "pf": null,
  "pts": null,
  "fg_pct": null,
  "fg3_pct": null,
  "ft_pct": null
}