export const BLANKAVG = [
    {name: 'games_played'},
    {name: 'Player_id'},
    {name: 'season'},
    {name: 'min'},
    {name: 'fgm'},
    {name: 'fga'},  
    {name: 'fg3m'},
    {name: 'fg3a'},
    {name: 'fga'},
    {name: 'ftm'},
    {name: 'oreb'},
    {name: 'dreb'},  
    {name: 'reb'},
    {name: 'ast'},
    {name: 'stl'}, 
    {name: 'blk'},
    {name: 'turnover'},
    {name: 'pf'},
    {name: 'pts'},
    {name: 'fg_pct'}, 
    {name: 'fg3_pct'},
    {name: 'ft_pct'}
  ]